config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles, only: %i[index show]

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :articles
    resources :users
  end

  devise_for :users, path: '',
                     skip: %i[passwords registrations],
                     path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
end

app/models/admin.rb
class Admin < User
  has_many :articles, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :admin

  validates :title, presence: true
  validates :visibility, inclusion: { in: %w[private public] }
  validates :reference, uniqueness: true, allow_blank: true
  has_rich_text :content

  scope :published, -> { where(published: true) }
  scope :public_visible, -> { where(visibility: 'public') }

  after_create :set_unique_reference

  private

  def set_unique_reference
    unique_reference = generate_unique_reference
    if Article.all.pluck(:reference).include?(unique_reference)
      set_unique_reference
    else
      update(reference: unique_reference)
    end
  end

  def generate_unique_reference
    string = '-------------------'
    chars_indexes = [0, 1, 2, 8, 9, 10, 16, 17, 18]
    numbers_indexes = [4, 5, 6, 12, 13, 14]
    chars = ('A'..'Z').to_a
    chars_indexes.each { |index| string[index] = chars.sample }
    numbers_indexes.each { |index| string[index] = rand(0..9).to_s }
    string
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.includes([:rich_text_content])
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params.merge(admin_id: current_user.id))

    if @article.save
      redirect_to admin_article_path(@article), notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to admin_article_path(@article), notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :visibility, :published)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  before_action :admin_required!

  private

  def admin_required!
    redirect_to root_path, alert: 'You are not athorized to view this page.' unless current_user.is_a?(Admin)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index; end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_path(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def after_sign_in_path_for(_admin)
    current_user.is_a?(Admin) ? admin_path : root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: :show

  def index
    @articles = if current_user
                  Article.published.includes([:rich_text_content])
                else
                  Article.published.public_visible.includes([:rich_text_content])
                end
  end

  def show
    return if current_user

    redirect_to root_path, alert: 'You are not athorized to view this page.' if @article.visibility == 'private'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success' then 'alert-success'
    when 'error' then 'alert-danger'
    when 'alert' then 'alert-warning'
    when 'notice' then 'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.image? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>
  <% if blob.video? %>
    <%= video_tag url_for(blob.attachable),
    preload: "auto",
    controls: "controls",
    width: "640",
    height: "360" %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_navigation.html.erb
<nav class="navbar navbar-light bg-light mb-3">
  <%= link_to 'Articles', root_path, class: 'navbar-brand' %>
  <%= link_to 'Admin panel', admin_path %>
  <span class="navbar-text">
    Welcome, <b>Admin</b> | <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </span>
</nav>

app/views/admin/articles/_article.html.erb
<tr>
  <td><%= article.title %></td>
  <td><%= article.content %></td>
  <td><%= article.visibility %></td>
  <td><%= article.reference %></td>
  <td><%= article.published %></td>
  <td><%= link_to 'Show', admin_article_path(article) %></td>
  <td><%= link_to 'Edit', edit_admin_article_path(article) %></td>
  <td><%= link_to 'Destroy', admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/articles/_form.html.erb
<%= form_with(model: [:admin, article], local: true) do |form| %>
  <%= render 'shared/errors', resource: article %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= form.label :visibility %>
    <%= form.select :visibility, ['private', 'public'], selected: 'private' %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<h1>Articles</h1>

<%= link_to 'New Article', new_admin_article_path %>

<%= render 'shared/errors', resource: @article %>

<table class="table mt-3">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Visibility</th>
      <th>Reference</th>
      <th>Published</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @articles %>
  </tbody>
</table>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Visibility:</strong>
  <%= @article.visibility %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @article.reference %>
</p>

<p>
  <strong>Published:</strong>
  <%= @article.published %>
</p>

<%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/dashboard/index.html.erb
<p><%= link_to 'Manage Users', admin_users_path %></p>
<p><%= link_to 'Manage Articles', admin_articles_path %></p>

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], local: true) do |form| %>
  <%= render 'shared/errors', resource: user %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.email %></td>
  <td><%= user.type %></td>
  <td><%= link_to 'Show', admin_user_path(user) %></td>
  <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
  <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= link_to 'New User', new_admin_user_path %>

<%= render 'shared/errors', resource: @user %>

<table class="table mt-3">
  <thead>
    <tr>
      <th>Email</th>
      <th>Type</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.type %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user.type %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/articles/_article.html.erb
<tr>
  <td><%= article.title %></td>
  <td><%= article.content %></td>
  <td><%= link_to 'Show', article %></td>
</tr>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= form.label :visibility %>
    <%= form.text_field :visibility %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<% content_for :meta_head do %>
    <title>Articles</title>
<% end %>

<h1>Articles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @articles %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% content_for :meta_head do %>
  <title><%= @article.title %></title>
  <meta name="description" content="<%= truncate(@article.content.to_plain_text, length: 100) %>" />
  <meta property="og:title" content="<%= @article.title %>" />
  <meta property="og:description" content="<%= truncate(@article.content.to_plain_text, length: 100) %>" />
  <meta property="og:type" content="article"/>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Back', articles_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-light mb-3">
  <%= link_to 'Articles', root_path, class: 'navbar-brand' %>
  <%= link_to 'Admin panel', admin_path if current_user.is_a?(Admin) %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= current_user.email %></b> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin panel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://vjs.zencdn.net/7.8.3/video-js.css" rel="stylesheet" />
  </head>

  <body>
    <%= render 'admin/navigation' %>
    <div class="container">
      <%= render partial: 'shared/flash', flash: flash %>
      <%= yield %>
    </div>
    <script src="https://vjs.zencdn.net/7.8.3/video.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :meta_head %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://vjs.zencdn.net/7.8.3/video-js.css" rel="stylesheet" />
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render partial: 'shared/flash', flash: flash %>
      <%= yield %>
    </div>
    <script src="https://vjs.zencdn.net/7.8.3/video.js"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div do %>
    <h3><%= pluralize(resource.errors.count, "error") %> detected:</h3>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
      <%= msg %>
    </div>
  <% end %>
</div>